"""add qfi measure

Revision ID: 09ee6c5bace8
Revises: 1700085bcdc8
Create Date: 2024-09-17 18:22:25.297561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ee6c5bace8'
down_revision: Union[str, None] = '1700085bcdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N12', sa.Column('qfi_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N12', sa.Column('qfi_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('qfi_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('qfi_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('qfi_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('qfi_post_anneal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'qfi_post_anneal')
    op.drop_column('instances_N8', 'qfi_fair_sampling')
    op.drop_column('instances_N16', 'qfi_post_anneal')
    op.drop_column('instances_N16', 'qfi_fair_sampling')
    op.drop_column('instances_N12', 'qfi_post_anneal')
    op.drop_column('instances_N12', 'qfi_fair_sampling')
    # ### end Alembic commands ###
