"""add hamming dist column

Revision ID: 13bee5d56160
Revises: 55862f48054f
Create Date: 2024-05-22 15:45:10.628947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13bee5d56160'
down_revision: Union[str, None] = '55862f48054f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N8', sa.Column('max_inter_gs_hd', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'max_inter_gs_hd')
    # ### end Alembic commands ###
