"""add overlap dist cols

Revision ID: 2085a187e672
Revises: 13bee5d56160
Create Date: 2024-05-23 10:09:31.701617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2085a187e672'
down_revision: Union[str, None] = '13bee5d56160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N8', sa.Column('overlap_dist', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('od_mean', sa.REAL(), nullable=True))
    op.add_column('instances_N8', sa.Column('od_variance', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'od_variance')
    op.drop_column('instances_N8', 'od_mean')
    op.drop_column('instances_N8', 'overlap_dist')
    # ### end Alembic commands ###
