"""add diagonalization info cols

Revision ID: 4e7b901856a8
Revises: 9de196d45749
Create Date: 2024-07-09 14:57:18.136718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7b901856a8'
down_revision: Union[str, None] = '9de196d45749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N12', sa.Column('diag_run_h_array', sa.JSON(), nullable=True))
    op.add_column('instances_N12', sa.Column('diag_run_fidelities', sa.JSON(), nullable=True))
    op.add_column('instances_N12', sa.Column('diag_run_e_gaps', sa.JSON(), nullable=True))
    op.add_column('instances_N12', sa.Column('diag_run_failure', sa.Boolean(), nullable=True))
    op.add_column('instances_N8', sa.Column('diag_run_h_array', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('diag_run_fidelities', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('diag_run_e_gaps', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('diag_run_failure', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'diag_run_failure')
    op.drop_column('instances_N8', 'diag_run_e_gaps')
    op.drop_column('instances_N8', 'diag_run_fidelities')
    op.drop_column('instances_N8', 'diag_run_h_array')
    op.drop_column('instances_N12', 'diag_run_failure')
    op.drop_column('instances_N12', 'diag_run_e_gaps')
    op.drop_column('instances_N12', 'diag_run_fidelities')
    op.drop_column('instances_N12', 'diag_run_h_array')
    # ### end Alembic commands ###
