"""add large n table

Revision ID: 57015df7028b
Revises: ba4d37f79e6e
Create Date: 2025-04-17 09:29:07.662521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57015df7028b'
down_revision: Union[str, None] = 'ba4d37f79e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('large_n',
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('ground_states', sa.JSON(), nullable=False),
    sa.Column('degeneracy', sa.Integer(), nullable=True),
    sa.Column('reduced_gs', sa.JSON(), nullable=True),
    sa.Column('overlap_dist', sa.JSON(), nullable=True),
    sa.Column('od_mean', sa.REAL(), nullable=True),
    sa.Column('od_variance', sa.REAL(), nullable=True),
    sa.Column('n_eff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('size', 'seed')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('large_n')
    # ### end Alembic commands ###
