"""add post anneal hamming dist

Revision ID: 5f4231f604d2
Revises: bcb545b79c51
Create Date: 2024-05-23 14:14:37.493205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4231f604d2'
down_revision: Union[str, None] = 'bcb545b79c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N8', sa.Column('post_anneal_max_inter_gs_hd', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'post_anneal_max_inter_gs_hd')
    # ### end Alembic commands ###
