"""add full gs cols

Revision ID: 6ebac0eb1932
Revises: 57015df7028b
Create Date: 2025-04-21 22:00:23.574721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebac0eb1932'
down_revision: Union[str, None] = '57015df7028b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N12', sa.Column('full_gs_od_variance', sa.REAL(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_post_anneal_od_variance', sa.REAL(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_disc_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_disc_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_qfi_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_qfi_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_od_variance', sa.REAL(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_post_anneal_od_variance', sa.REAL(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_disc_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_disc_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_qfi_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_qfi_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_od_variance', sa.REAL(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_post_anneal_od_variance', sa.REAL(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_disc_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_disc_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_qfi_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_qfi_post_anneal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'full_gs_qfi_post_anneal')
    op.drop_column('instances_N8', 'full_gs_qfi_fair_sampling')
    op.drop_column('instances_N8', 'full_gs_disc_post_anneal')
    op.drop_column('instances_N8', 'full_gs_disc_fair_sampling')
    op.drop_column('instances_N8', 'full_gs_post_anneal_od_variance')
    op.drop_column('instances_N8', 'full_gs_od_variance')
    op.drop_column('instances_N16', 'full_gs_qfi_post_anneal')
    op.drop_column('instances_N16', 'full_gs_qfi_fair_sampling')
    op.drop_column('instances_N16', 'full_gs_disc_post_anneal')
    op.drop_column('instances_N16', 'full_gs_disc_fair_sampling')
    op.drop_column('instances_N16', 'full_gs_post_anneal_od_variance')
    op.drop_column('instances_N16', 'full_gs_od_variance')
    op.drop_column('instances_N12', 'full_gs_qfi_post_anneal')
    op.drop_column('instances_N12', 'full_gs_qfi_fair_sampling')
    op.drop_column('instances_N12', 'full_gs_disc_post_anneal')
    op.drop_column('instances_N12', 'full_gs_disc_fair_sampling')
    op.drop_column('instances_N12', 'full_gs_post_anneal_od_variance')
    op.drop_column('instances_N12', 'full_gs_od_variance')
    # ### end Alembic commands ###
