"""add disconnectivity cols

Revision ID: 874cc305661a
Revises: 4e7b901856a8
Create Date: 2024-07-22 10:33:35.764015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874cc305661a'
down_revision: Union[str, None] = '4e7b901856a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N12', sa.Column('disc_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N12', sa.Column('disc_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('disc_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('disc_post_anneal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'disc_post_anneal')
    op.drop_column('instances_N8', 'disc_fair_sampling')
    op.drop_column('instances_N12', 'disc_post_anneal')
    op.drop_column('instances_N12', 'disc_fair_sampling')
    # ### end Alembic commands ###
