"""add N12

Revision ID: 91c2e1ede06d
Revises: 5f4231f604d2
Create Date: 2024-05-24 18:46:37.089313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c2e1ede06d'
down_revision: Union[str, None] = '5f4231f604d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances_N12',
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('Jij_matrix', sa.JSON(), nullable=False),
    sa.Column('ground_states', sa.JSON(), nullable=False),
    sa.Column('degeneracy', sa.Integer(), nullable=True),
    sa.Column('reduced_gs', sa.JSON(), nullable=True),
    sa.Column('max_inter_gs_hd', sa.Integer(), nullable=True),
    sa.Column('overlap_dist', sa.JSON(), nullable=True),
    sa.Column('od_mean', sa.REAL(), nullable=True),
    sa.Column('od_variance', sa.REAL(), nullable=True),
    sa.Column('post_anneal_gs_probs', sa.JSON(), nullable=True),
    sa.Column('post_anneal_supp_ratio', sa.REAL(), nullable=True),
    sa.Column('post_anneal_gs', sa.JSON(), nullable=True),
    sa.Column('post_anneal_deg', sa.Integer(), nullable=True),
    sa.Column('post_anneal_overlap_dist', sa.JSON(), nullable=True),
    sa.Column('post_anneal_od_mean', sa.REAL(), nullable=True),
    sa.Column('post_anneal_od_variance', sa.REAL(), nullable=True),
    sa.Column('post_anneal_max_inter_gs_hd', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seed')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances_N12')
    # ### end Alembic commands ###
