"""post anneal overlap changes

Revision ID: 9de196d45749
Revises: 91c2e1ede06d
Create Date: 2024-05-30 13:26:57.001221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9de196d45749'
down_revision: Union[str, None] = '91c2e1ede06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N12', 'post_anneal_max_inter_gs_hd')
    op.drop_column('instances_N12', 'post_anneal_deg')
    op.drop_column('instances_N12', 'post_anneal_gs')
    op.drop_column('instances_N8', 'post_anneal_max_inter_gs_hd')
    op.drop_column('instances_N8', 'post_anneal_deg')
    op.drop_column('instances_N8', 'post_anneal_gs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N8', sa.Column('post_anneal_gs', sqlite.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_deg', sa.INTEGER(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_max_inter_gs_hd', sa.INTEGER(), nullable=True))
    op.add_column('instances_N12', sa.Column('post_anneal_gs', sqlite.JSON(), nullable=True))
    op.add_column('instances_N12', sa.Column('post_anneal_deg', sa.INTEGER(), nullable=True))
    op.add_column('instances_N12', sa.Column('post_anneal_max_inter_gs_hd', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
