"""add dist cols

Revision ID: ba4d37f79e6e
Revises: 09ee6c5bace8
Create Date: 2024-11-13 10:22:07.064125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4d37f79e6e'
down_revision: Union[str, None] = '09ee6c5bace8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N12', sa.Column('dist_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N12', sa.Column('dist_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('dist_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N16', sa.Column('dist_post_anneal', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('dist_fair_sampling', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('dist_post_anneal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'dist_post_anneal')
    op.drop_column('instances_N8', 'dist_fair_sampling')
    op.drop_column('instances_N16', 'dist_post_anneal')
    op.drop_column('instances_N16', 'dist_fair_sampling')
    op.drop_column('instances_N12', 'dist_post_anneal')
    op.drop_column('instances_N12', 'dist_fair_sampling')
    # ### end Alembic commands ###
