"""add post annealing cols

Revision ID: bcb545b79c51
Revises: 2085a187e672
Create Date: 2024-05-23 11:23:31.859187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb545b79c51'
down_revision: Union[str, None] = '2085a187e672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N8', sa.Column('post_anneal_gs_probs', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_supp_ratio', sa.REAL(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_gs', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_deg', sa.Integer(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_overlap_dist', sa.JSON(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_od_mean', sa.REAL(), nullable=True))
    op.add_column('instances_N8', sa.Column('post_anneal_od_variance', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N8', 'post_anneal_od_variance')
    op.drop_column('instances_N8', 'post_anneal_od_mean')
    op.drop_column('instances_N8', 'post_anneal_overlap_dist')
    op.drop_column('instances_N8', 'post_anneal_deg')
    op.drop_column('instances_N8', 'post_anneal_gs')
    op.drop_column('instances_N8', 'post_anneal_supp_ratio')
    op.drop_column('instances_N8', 'post_anneal_gs_probs')
    # ### end Alembic commands ###
