"""remove disc cols

Revision ID: ffb9a86b1b95
Revises: 6ebac0eb1932
Create Date: 2025-04-21 22:06:31.118341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb9a86b1b95'
down_revision: Union[str, None] = '6ebac0eb1932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances_N12', 'full_gs_disc_fair_sampling')
    op.drop_column('instances_N12', 'full_gs_disc_post_anneal')
    op.drop_column('instances_N16', 'full_gs_disc_fair_sampling')
    op.drop_column('instances_N16', 'full_gs_disc_post_anneal')
    op.drop_column('instances_N8', 'full_gs_disc_fair_sampling')
    op.drop_column('instances_N8', 'full_gs_disc_post_anneal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances_N8', sa.Column('full_gs_disc_post_anneal', sa.INTEGER(), nullable=True))
    op.add_column('instances_N8', sa.Column('full_gs_disc_fair_sampling', sa.INTEGER(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_disc_post_anneal', sa.INTEGER(), nullable=True))
    op.add_column('instances_N16', sa.Column('full_gs_disc_fair_sampling', sa.INTEGER(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_disc_post_anneal', sa.INTEGER(), nullable=True))
    op.add_column('instances_N12', sa.Column('full_gs_disc_fair_sampling', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
