"""gs and metrics

Revision ID: 0bb572237aa2
Revises: 445c98734ae6
Create Date: 2025-06-30 06:58:23.388162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb572237aa2'
down_revision: Union[str, Sequence[str], None] = '445c98734ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instancemetrics',
    sa.Column('N', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('fs_od', sa.JSON(), nullable=True),
    sa.Column('fs_od_mean', sa.Float(), nullable=True),
    sa.Column('fs_od_var', sa.Float(), nullable=True),
    sa.Column('fs_qfi', sa.Float(), nullable=True),
    sa.Column('pa_od', sa.JSON(), nullable=True),
    sa.Column('pa_od_mean', sa.Float(), nullable=True),
    sa.Column('pa_od_var', sa.Float(), nullable=True),
    sa.Column('pa_qfi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('N', 'seed')
    )
    op.add_column('instancegroundstates', sa.Column('reduced_gs', sa.JSON(), nullable=True))
    op.add_column('instancegroundstates', sa.Column('degeneracy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instancegroundstates', 'degeneracy')
    op.drop_column('instancegroundstates', 'reduced_gs')
    op.drop_table('instancemetrics')
    # ### end Alembic commands ###
